plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/liangfan/WorkBuddy/2026-06-03-17-01-15/management-deploy"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]